# Generated by Django 3.1.1 on 2020-09-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidindia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatedata',
            name='state_id',
            field=models.IntegerField(blank=True),
        ),
    ]
