# Generated by Django 3.1.1 on 2020-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidindia', '0002_auto_20200904_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTotalcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('total_corona_cases', models.IntegerField(blank=True)),
                ('confirmed_corona_cases', models.IntegerField(blank=True)),
                ('recovered_corona_cases', models.IntegerField(blank=True)),
                ('deaths_corona_cases', models.IntegerField(blank=True)),
            ],
        ),
    ]
